wm-timemons decomped
FireEmblemUniverse/fireemblem8u pull request #563
Opened 2024-01-25 14:59 UTC by MokhaLeee

2024-01-25 17:42 UTC, jiangzhengwenjz requested changes

2024-01-25 17:42 UTC, jiangzhengwenjz commented on src/worldmap_timemons.c
> +    _080C1822:
unused label

2024-01-25 17:42 UTC, jiangzhengwenjz commented on src/worldmap_timemons.c
> +                proc->ap_procs[i] = APProc_Create(Sprite_08A97AEC, (s16)x, (s16)y, 0x3880, 0, 7);
```suggestion
            if ((y >= 0 && y < 0xB0) && (x >= 0 && x < 0xF0))
                proc->ap_procs[i] = APProc_Create(Sprite_08A97AEC, x, y, 0x3880, 0, 7);
```

2024-01-25 17:42 UTC, jiangzhengwenjz commented on src/worldmap_timemons.c
> +    int r0, cnt, rn;
```suggestion
    int cnt, rn;
```

2024-01-26 02:30 UTC, MokhaLeee commented on src/worldmap_timemons.c
> +    int r0, cnt, rn;
updated

2024-01-26 04:10 UTC, merged